name: Pages

on:
  push:
    branches:
      - main  # default branch
    # 允许外部仓库事件触发
  repository_dispatch:
    types:
      - deploy
  # 每周日凌晨2点触发更新
  schedule:
    - cron: '0 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: '20.10.0'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          export TZ='Asia/Shanghai'
          npm install --prod
      # 拉取语雀信息
      - name: 拉取语雀/Notion的文章
        env:
          # 语雀相关环境变量          
          # 语雀（帐号密码方式）
          YUQUE_USERNAME: ${{ secrets.YUQUE_USERNAME }}
          YUQUE_PASSWORD: ${{ secrets.YUQUE_PASSWORD }}
          YUQUE_LOGIN: ${{secrets.YUQUE_LOGIN }}
          YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
          # 图床相关环境变量，github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
          ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
        run: |
          # 对应package.json中的script.sync
          npm run sync:post
      
      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "choodsire666"
          git config --global user.email "1609981289@qq.com"

      - name: 拉取代码
        uses: ad-m/github-pull-action@master
        with:
          # GITHUB_TOKEN为流水线内置变量，无需配置，可直接使用
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 提交yuque拉取的文章到GitHub仓库
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
          git add .
          git commit -m "更新文档" -a

      - name: 推送文章到仓库
        uses: ad-m/github-push-action@master
        with:
          # GITHUB_TOKEN为流水线内置变量，无需配置，可直接使用
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # 拉取b站信息
      - name: get bilibili
        run: npm run sync:bili

      # 生成Algolia搜索indexs
      - name: create indexs
        run: npm run sync:algolia

      # build
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
